### ISSUE TITLE
Specs de FoldersController falhando

### ISSUE THREAD

**Issue by guiocavalcanti** [redu/redu#1665]
```
1) FoldersController POST create should assign folder
     Failure/Error: post :create, params
     NoMethodError:
       undefined method `state' for nil:NilClass
     # ./app/models/folder.rb:65:in `can_upload_file?'
     # ./app/abilites/ability.rb:141:in `block in initialize'
     # ./app/controllers/folders_controller.rb:150:in `list'
     # ./app/controllers/folders_controller.rb:93:in `block in create'
     # ./app/controllers/folders_controller.rb:91:in `create'
     # ./spec/controllers/folders_controller_spec.rb:25:in `block (3 levels) in <top (required)>'
     # -e:1:in `<main>'

  2) FoldersController POST create should assing space
     Failure/Error: post :create, params
     NoMethodError:
       undefined method `state' for nil:NilClass
     # ./app/models/folder.rb:65:in `can_upload_file?'
     # ./app/abilites/ability.rb:141:in `block in initialize'
     # ./app/controllers/folders_controller.rb:150:in `list'
     # ./app/controllers/folders_controller.rb:93:in `block in create'
     # ./app/controllers/folders_controller.rb:91:in `create'
     # ./spec/controllers/folders_controller_spec.rb:30:in `block (3 levels) in <top (required)>'
     # -e:1:in `<main>'

  3) FoldersController POST create should call FolderService.create
     Failure/Error: post :create, params
     NoMethodError:
       undefined method `state' for nil:NilClass
     # ./app/models/folder.rb:65:in `can_upload_file?'
     # ./app/abilites/ability.rb:141:in `block in initialize'
     # ./app/controllers/folders_controller.rb:150:in `list'
     # ./app/controllers/folders_controller.rb:93:in `block in create'
     # ./app/controllers/folders_controller.rb:91:in `create'
     # ./spec/controllers/folders_controller_spec.rb:36:in `block (3 levels) in <top (required)>'
     # -e:1:in `<main>'

  4) FoldersController POST create should set folder#user
     Failure/Error: post :create, params
     NoMethodError:
       undefined method `state' for nil:NilClass
     # ./app/models/folder.rb:65:in `can_upload_file?'
     # ./app/abilites/ability.rb:141:in `block in initialize'
     # ./app/controllers/folders_controller.rb:150:in `list'
     # ./app/controllers/folders_controller.rb:93:in `block in create'
     # ./app/controllers/folders_controller.rb:91:in `create'
     # ./spec/controllers/folders_controller_spec.rb:40:in `block (3 levels) in <top (required)>'
     # -e:1:in `<main>'

  5) FoldersController POST create should set folder#date_modified
     Failure/Error: post :create, params
     NoMethodError:
       undefined method `state' for nil:NilClass
     # ./app/models/folder.rb:65:in `can_upload_file?'
     # ./app/abilites/ability.rb:141:in `block in initialize'
     # ./app/controllers/folders_controller.rb:150:in `list'
     # ./app/controllers/folders_controller.rb:93:in `block in create'
     # ./app/controllers/folders_controller.rb:91:in `create'
     # ./spec/controllers/folders_controller_spec.rb:45:in `block (3 levels) in <top (required)>'
     # -e:1:in `<main>'

  6) FoldersController DELETE destroy should call FolderService.destroy
     Failure/Error: delete :destroy_folder, params
     NoMethodError:
       undefined method `state' for nil:NilClass
     # ./app/models/folder.rb:65:in `can_upload_file?'
     # ./app/abilites/ability.rb:141:in `block in initialize'
     # ./app/controllers/folders_controller.rb:150:in `list'
     # ./app/controllers/folders_controller.rb:128:in `block (2 levels) in destroy_folder'
     # ./app/controllers/folders_controller.rb:125:in `destroy_folder'
     # ./spec/controllers/folders_controller_spec.rb:55:in `block (3 levels) in <top (required)>'
     # -e:1:in `<main>'

  7) FoldersController POST update should assign parent folder
     Failure/Error: post :update, params
     NoMethodError:
       undefined method `state' for nil:NilClass
     # ./app/models/folder.rb:65:in `can_upload_file?'
     # ./app/abilites/ability.rb:141:in `block in initialize'
     # ./app/controllers/folders_controller.rb:150:in `list'
     # ./app/controllers/folders_controller.rb:113:in `block (2 levels) in update'
     # ./app/controllers/folders_controller.rb:112:in `update'
     # ./spec/controllers/folders_controller_spec.rb:65:in `block (3 levels) in <top (required)>'
     # -e:1:in `<main>'

  8) FoldersController POST update should call FolderService.update
     Failure/Error: post :update, params
     NoMethodError:
       undefined method `state' for nil:NilClass
     # ./app/models/folder.rb:65:in `can_upload_file?'
     # ./app/abilites/ability.rb:141:in `block in initialize'
     # ./app/controllers/folders_controller.rb:150:in `list'
     # ./app/controllers/folders_controller.rb:113:in `block (2 levels) in update'
     # ./app/controllers/folders_controller.rb:112:in `update'
     # ./spec/controllers/folders_controller_spec.rb:74:in `block (3 levels) in <top (required)>'
     # -e:1:in `<main>'

  9) FoldersController Myfiles DELETE destroy_file should call MyfileService.destroy
     Failure/Error: delete :destroy_file, params
     NoMethodError:
       undefined method `state' for nil:NilClass
     # ./app/models/folder.rb:65:in `can_upload_file?'
     # ./app/abilites/ability.rb:141:in `block in initialize'
     # ./app/controllers/folders_controller.rb:150:in `list'
     # ./app/controllers/folders_controller.rb:30:in `block (2 levels) in destroy_file'
     # ./app/controllers/folders_controller.rb:23:in `destroy_file'
     # ./spec/controllers/folders_controller_spec.rb:121:in `block (4 levels) in <top (required)>'
     # -e:1:in `<main>'

  10) FoldersController Myfiles DELETE destroy_file should assign myfile
     Failure/Error: delete :destroy_file, params
     NoMethodError:
       undefined method `state' for nil:NilClass
     # ./app/models/folder.rb:65:in `can_upload_file?'
     # ./app/abilites/ability.rb:141:in `block in initialize'
     # ./app/controllers/folders_controller.rb:150:in `list'
     # ./app/controllers/folders_controller.rb:30:in `block (2 levels) in destroy_file'
     # ./app/controllers/folders_controller.rb:23:in `destroy_file'
     # ./spec/controllers/folders_controller_spec.rb:125:in `block (4 levels) in <top (required)>'
     # -e:1:in `<main>'

```
