### ISSUE TITLE
Specs de PresenceController falhando

### ISSUE THREAD

**Issue by guiocavalcanti** [redu/redu#716]
Acontece ao rodar a suite completa com `rspec spec` ou `rake spec`.

```
Failures:

  1) PresenceController GET last_messages_with returns log conversation
     Failure/Error: response.body.should == payload.to_json
       expected: "[{\"name\":\"Usu\\u00e1rio 1166 da Silva 1166\",\"thumbnail\":\"/images/new/missing_users_thumb_24.png\",\"text\":\"Uma nova mensagem de texto - 9\",\"time\":\"hoje, 12:50\",\"user_id\":1169},{\"name\":\"Usu\\u00e1rio 1167 da Silva 1167\",\"thumbnail\":\"/images/new/missing_users_thumb_24.png\",\"text\":\"Uma nova mensagem de texto - 11\",\"time\":\"hoje, 12:50\",\"user_id\":1170},{\"name\":\"Usu\\u00e1rio 1166 da Silva 1166\",\"thumbnail\":\"/images/new/missing_users_thumb_24.png\",\"text\":\"Uma nova mensagem de texto - 13\",\"time\":\"hoje, 12:50\",\"user_id\":1169}]"
            got: "[{\"name\":\"Usu\\u00e1rio 1167 da Silva 1167\",\"thumbnail\":\"/images/new/missing_users_thumb_24.png\",\"text\":\"Uma nova mensagem de texto - 11\",\"time\":\"hoje, 12:50\",\"user_id\":1170},{\"name\":\"Usu\\u00e1rio 1166 da Silva 1166\",\"thumbnail\":\"/images/new/missing_users_thumb_24.png\",\"text\":\"Uma nova mensagem de texto - 9\",\"time\":\"hoje, 12:50\",\"user_id\":1169},{\"name\":\"Usu\\u00e1rio 1166 da Silva 1166\",\"thumbnail\":\"/images/new/missing_users_thumb_24.png\",\"text\":\"Uma nova mensagem de texto - 13\",\"time\":\"hoje, 12:50\",\"user_id\":1169}]" (using ==)
     # ./spec/controllers/presence_controller_spec.rb:283
```
